[package]
name = "roguelike"
version = "0.1.0"
authors = ["Parker Spielvogel <paspielvogel@gmail.com>"]
edition = "2018"

[dependencies]
tcod = "0.15.0"
specs = "0.14.3"
specs-derive = "0.4.0"
rand = "0.5.0"
sha-1 = "0.8.1"
sha2 = "0.8.0"
time = "0.1.42"
